apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense-namespace
spec:
  type: LoadBalancer
  selector:
    tier: web
    component: frontend
    project: expense 
  ports:
  - protocol: TCP
    port: 80 #serviceport differs from target port
    targetPort: {{ .Values.configmap.port }}